### ISSUE TITLE
HTML Element type to have children field?

### ISSUE THREAD

**Issue by mattludwigs** [knledg/elm-dom-ports#1]
thinking we should add the `children` field to the html element type. I can make  a PR if you agree. 

The use case would be when a parent element is clicked we want to do something to 1 or more children.

One solution would be use [elm-pub-sub](https://github.com/knledg/elm-pub-sub-ports), but that seems like some extra indirection for some things.

What are your thoughts?

**Comment by paulstatezny** [comment]
Great idea.

I wanted `HtmlElement` to mirror the structure of [HtmlElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) in JavaScript as much as possible, but I've only been adding properties as use cases arise.

How far nested would we go? Would we return every descendant of the node? This could be a pretty big payload. (Not sure if this would ever be a burden computationally.)

**Comment by mattludwigs** [comment]
Hm upon further investigation `HtmlElment` from the DOM Api does not have `children`


It looks like it is part of `Element` which specific elements inherent from like `HTMLDivElement`

Not sure the best way to handle it. There might be some insight on the [PureScript DOM library](https://pursuit.purescript.org/packages/purescript-dom/3.3.1)

**Comment by paulstatezny** [comment]
No I think you were right: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children

Need to verify, but I think `children` will just be absent if there are none. (Thereby making the element not a ParentNode.)

**Comment by mattludwigs** [comment]
I guess the real question is the `DomPorts` Api `HtmlElement` the same as the DOM Api, or is that really a `Element`

**Comment by paulstatezny** [comment]
That's a good point, there might be some renaming in order.

It already contains fields that only sub-types of `HtmlElement` will have. (Such as `value` from `HTMLInputElement` and `pathname` from `HTMLAnchorElement`.) So there's some inconsistency. I'm open to ideas! 😃

**Comment by mattludwigs** [comment]
Maybe we stick with it just to add the `children` and we can plan on how we want to resolve the DOM API to DomPorts types?

that will solve the use case I talked about now, but we an revisit the Api with a little more thought.
